### PR TITLE
fix: Objects without any key can also be flatted, causing the control display to error

### LINKED ISSUE #14: [Bug] Objects without any key can also be flatted, causing the control display to error
Hi, I have solved this problem.

reproduce:
just
```ts
const meta = {
  component: YourComponent,
  argTypes: {
    style: { control: 'object' },
    'config.fetchParam': {
      control: 'object'
    },
    'config.jumpParam': {
      control: 'object',
    },
  } as ArgTypes,
  parameters: {
    deepControls: { enabled: true },
  },
} satisfies Meta<typeof YourComponent>;

export const Default: Story = {
  args: {
    data: {
      fetchParam: {}, // 1. will be fixed in this pr!
      jumpParam: {a:1}, // 2. There is still an issue that requires the user to explicitly set argTypes manually. fixed
    },
    style: {}, // 3. As predicted, showed
    data: {}, // 4. As predicted, argTypes must be set explicitly manually
  },
};
```

bug:
image

Desired result:
image

### PR DESCRIPTION
**Pull request by eric-gitta-moore**
```js
  /**
     * skip flatten if follow these rules:
     * 1. the value is not an object
     * 2. the value is an object but has no keys
     * 3. the value is an object and has keys but argTypes are not explicitly set by the user
     */
```

screenshot:
image

Please forgive me if I don't have more time to write unit tests

Closes #14

### CODE REVIEW

**Comment by eliasm307** [comment]
Hello @eric-gitta-moore thanks for the PR, I haven't had a chance to go through this yet but from a glance it looks like tour commit is not based on the latest main branch somehow?

**Comment by eric-gitta-moore** [comment]
> Hello @eric-gitta-moore thanks for the PR, I haven't had a chance to go through this yet but from a glance it looks like tour commit is not based on the latest main branch somehow?

Yeah, that's what I find strange. I forked from the latest tag

**Comment by eliasm307** [comment]
Instead of the latest tag try to rebase on the latest commit of the main branch

**Comment by eliasm307** [comment]
The commits after the latest tag are for internal changes that didn't need the package to be published.

I'll review this once the branch is updated

**Comment by eliasm307** [comment]
@eric-gitta-moore are you still working on this?

**Pull request closed without merging**
